// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYxWm236NicoPd6H6FdhU4TjcqAkSN2pI',
    appId: '1:405077494000:web:30a6404d52c13f1cb8da35',
    messagingSenderId: '405077494000',
    projectId: 'smile-monitoring',
    authDomain: 'smile-monitoring.firebaseapp.com',
    storageBucket: 'smile-monitoring.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG8BgyE-bt4zo2iJixJR86Qx_B3owROvo',
    appId: '1:405077494000:android:ce44a8d49f650052b8da35',
    messagingSenderId: '405077494000',
    projectId: 'smile-monitoring',
    storageBucket: 'smile-monitoring.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS0lXQdn9ataX7_wK5S0L2EdwswkQk1KU',
    appId: '1:405077494000:ios:438afa5b67c53c94b8da35',
    messagingSenderId: '405077494000',
    projectId: 'smile-monitoring',
    storageBucket: 'smile-monitoring.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS0lXQdn9ataX7_wK5S0L2EdwswkQk1KU',
    appId: '1:405077494000:ios:438afa5b67c53c94b8da35',
    messagingSenderId: '405077494000',
    projectId: 'smile-monitoring',
    storageBucket: 'smile-monitoring.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYxWm236NicoPd6H6FdhU4TjcqAkSN2pI',
    appId: '1:405077494000:web:7cbdb987ad1841c0b8da35',
    messagingSenderId: '405077494000',
    projectId: 'smile-monitoring',
    authDomain: 'smile-monitoring.firebaseapp.com',
    storageBucket: 'smile-monitoring.firebasestorage.app',
  );
}
